package de.platfrom.tele.blueconn;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TeleCommunication.proto

public final class TeleCommunication {
  private TeleCommunication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ControlMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ControlMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 speed_x = 1;</code>
     * @return The speedX.
     */
    int getSpeedX();

    /**
     * <code>int32 speed_y = 2;</code>
     * @return The speedY.
     */
    int getSpeedY();

    /**
     * <code>int32 speed_rot = 3;</code>
     * @return The speedRot.
     */
    int getSpeedRot();

    /**
     * <code>int32 pan = 4;</code>
     * @return The pan.
     */
    int getPan();

    /**
     * <code>int32 tilt = 5;</code>
     * @return The tilt.
     */
    int getTilt();
  }
  /**
   * Protobuf type {@code ControlMessage}
   */
  public  static final class ControlMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ControlMessage)
      ControlMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlMessage.newBuilder() to construct.
    private ControlMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ControlMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              speedX_ = input.readInt32();
              break;
            }
            case 16: {

              speedY_ = input.readInt32();
              break;
            }
            case 24: {

              speedRot_ = input.readInt32();
              break;
            }
            case 32: {

              pan_ = input.readInt32();
              break;
            }
            case 40: {

              tilt_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TeleCommunication.internal_static_ControlMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TeleCommunication.internal_static_ControlMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeleCommunication.ControlMessage.class, TeleCommunication.ControlMessage.Builder.class);
    }

    public static final int SPEED_X_FIELD_NUMBER = 1;
    private int speedX_;
    /**
     * <code>int32 speed_x = 1;</code>
     * @return The speedX.
     */
    public int getSpeedX() {
      return speedX_;
    }

    public static final int SPEED_Y_FIELD_NUMBER = 2;
    private int speedY_;
    /**
     * <code>int32 speed_y = 2;</code>
     * @return The speedY.
     */
    public int getSpeedY() {
      return speedY_;
    }

    public static final int SPEED_ROT_FIELD_NUMBER = 3;
    private int speedRot_;
    /**
     * <code>int32 speed_rot = 3;</code>
     * @return The speedRot.
     */
    public int getSpeedRot() {
      return speedRot_;
    }

    public static final int PAN_FIELD_NUMBER = 4;
    private int pan_;
    /**
     * <code>int32 pan = 4;</code>
     * @return The pan.
     */
    public int getPan() {
      return pan_;
    }

    public static final int TILT_FIELD_NUMBER = 5;
    private int tilt_;
    /**
     * <code>int32 tilt = 5;</code>
     * @return The tilt.
     */
    public int getTilt() {
      return tilt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (speedX_ != 0) {
        output.writeInt32(1, speedX_);
      }
      if (speedY_ != 0) {
        output.writeInt32(2, speedY_);
      }
      if (speedRot_ != 0) {
        output.writeInt32(3, speedRot_);
      }
      if (pan_ != 0) {
        output.writeInt32(4, pan_);
      }
      if (tilt_ != 0) {
        output.writeInt32(5, tilt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (speedX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, speedX_);
      }
      if (speedY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, speedY_);
      }
      if (speedRot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, speedRot_);
      }
      if (pan_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pan_);
      }
      if (tilt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, tilt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TeleCommunication.ControlMessage)) {
        return super.equals(obj);
      }
      TeleCommunication.ControlMessage other = (TeleCommunication.ControlMessage) obj;

      if (getSpeedX()
          != other.getSpeedX()) return false;
      if (getSpeedY()
          != other.getSpeedY()) return false;
      if (getSpeedRot()
          != other.getSpeedRot()) return false;
      if (getPan()
          != other.getPan()) return false;
      if (getTilt()
          != other.getTilt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SPEED_X_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedX();
      hash = (37 * hash) + SPEED_Y_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedY();
      hash = (37 * hash) + SPEED_ROT_FIELD_NUMBER;
      hash = (53 * hash) + getSpeedRot();
      hash = (37 * hash) + PAN_FIELD_NUMBER;
      hash = (53 * hash) + getPan();
      hash = (37 * hash) + TILT_FIELD_NUMBER;
      hash = (53 * hash) + getTilt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TeleCommunication.ControlMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.ControlMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.ControlMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.ControlMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TeleCommunication.ControlMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.ControlMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TeleCommunication.ControlMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ControlMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ControlMessage)
        TeleCommunication.ControlMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TeleCommunication.internal_static_ControlMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TeleCommunication.internal_static_ControlMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeleCommunication.ControlMessage.class, TeleCommunication.ControlMessage.Builder.class);
      }

      // Construct using TeleCommunication.ControlMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        speedX_ = 0;

        speedY_ = 0;

        speedRot_ = 0;

        pan_ = 0;

        tilt_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TeleCommunication.internal_static_ControlMessage_descriptor;
      }

      @java.lang.Override
      public TeleCommunication.ControlMessage getDefaultInstanceForType() {
        return TeleCommunication.ControlMessage.getDefaultInstance();
      }

      @java.lang.Override
      public TeleCommunication.ControlMessage build() {
        TeleCommunication.ControlMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TeleCommunication.ControlMessage buildPartial() {
        TeleCommunication.ControlMessage result = new TeleCommunication.ControlMessage(this);
        result.speedX_ = speedX_;
        result.speedY_ = speedY_;
        result.speedRot_ = speedRot_;
        result.pan_ = pan_;
        result.tilt_ = tilt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeleCommunication.ControlMessage) {
          return mergeFrom((TeleCommunication.ControlMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeleCommunication.ControlMessage other) {
        if (other == TeleCommunication.ControlMessage.getDefaultInstance()) return this;
        if (other.getSpeedX() != 0) {
          setSpeedX(other.getSpeedX());
        }
        if (other.getSpeedY() != 0) {
          setSpeedY(other.getSpeedY());
        }
        if (other.getSpeedRot() != 0) {
          setSpeedRot(other.getSpeedRot());
        }
        if (other.getPan() != 0) {
          setPan(other.getPan());
        }
        if (other.getTilt() != 0) {
          setTilt(other.getTilt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeleCommunication.ControlMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeleCommunication.ControlMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int speedX_ ;
      /**
       * <code>int32 speed_x = 1;</code>
       * @return The speedX.
       */
      public int getSpeedX() {
        return speedX_;
      }
      /**
       * <code>int32 speed_x = 1;</code>
       * @param value The speedX to set.
       * @return This builder for chaining.
       */
      public Builder setSpeedX(int value) {
        
        speedX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed_x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeedX() {
        
        speedX_ = 0;
        onChanged();
        return this;
      }

      private int speedY_ ;
      /**
       * <code>int32 speed_y = 2;</code>
       * @return The speedY.
       */
      public int getSpeedY() {
        return speedY_;
      }
      /**
       * <code>int32 speed_y = 2;</code>
       * @param value The speedY to set.
       * @return This builder for chaining.
       */
      public Builder setSpeedY(int value) {
        
        speedY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed_y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeedY() {
        
        speedY_ = 0;
        onChanged();
        return this;
      }

      private int speedRot_ ;
      /**
       * <code>int32 speed_rot = 3;</code>
       * @return The speedRot.
       */
      public int getSpeedRot() {
        return speedRot_;
      }
      /**
       * <code>int32 speed_rot = 3;</code>
       * @param value The speedRot to set.
       * @return This builder for chaining.
       */
      public Builder setSpeedRot(int value) {
        
        speedRot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed_rot = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeedRot() {
        
        speedRot_ = 0;
        onChanged();
        return this;
      }

      private int pan_ ;
      /**
       * <code>int32 pan = 4;</code>
       * @return The pan.
       */
      public int getPan() {
        return pan_;
      }
      /**
       * <code>int32 pan = 4;</code>
       * @param value The pan to set.
       * @return This builder for chaining.
       */
      public Builder setPan(int value) {
        
        pan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pan = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPan() {
        
        pan_ = 0;
        onChanged();
        return this;
      }

      private int tilt_ ;
      /**
       * <code>int32 tilt = 5;</code>
       * @return The tilt.
       */
      public int getTilt() {
        return tilt_;
      }
      /**
       * <code>int32 tilt = 5;</code>
       * @param value The tilt to set.
       * @return This builder for chaining.
       */
      public Builder setTilt(int value) {
        
        tilt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tilt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTilt() {
        
        tilt_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ControlMessage)
    }

    // @@protoc_insertion_point(class_scope:ControlMessage)
    private static final TeleCommunication.ControlMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TeleCommunication.ControlMessage();
    }

    public static TeleCommunication.ControlMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlMessage>
        PARSER = new com.google.protobuf.AbstractParser<ControlMessage>() {
      @java.lang.Override
      public ControlMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TeleCommunication.ControlMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DistancesMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DistancesMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 dist1 = 1;</code>
     * @return The dist1.
     */
    int getDist1();

    /**
     * <code>int32 dist2 = 2;</code>
     * @return The dist2.
     */
    int getDist2();

    /**
     * <code>int32 dist3 = 3;</code>
     * @return The dist3.
     */
    int getDist3();

    /**
     * <code>int32 dist4 = 4;</code>
     * @return The dist4.
     */
    int getDist4();
  }
  /**
   * Protobuf type {@code DistancesMessage}
   */
  public  static final class DistancesMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DistancesMessage)
      DistancesMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DistancesMessage.newBuilder() to construct.
    private DistancesMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DistancesMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DistancesMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DistancesMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dist1_ = input.readInt32();
              break;
            }
            case 16: {

              dist2_ = input.readInt32();
              break;
            }
            case 24: {

              dist3_ = input.readInt32();
              break;
            }
            case 32: {

              dist4_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TeleCommunication.internal_static_DistancesMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TeleCommunication.internal_static_DistancesMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeleCommunication.DistancesMessage.class, TeleCommunication.DistancesMessage.Builder.class);
    }

    public static final int DIST1_FIELD_NUMBER = 1;
    private int dist1_;
    /**
     * <code>int32 dist1 = 1;</code>
     * @return The dist1.
     */
    public int getDist1() {
      return dist1_;
    }

    public static final int DIST2_FIELD_NUMBER = 2;
    private int dist2_;
    /**
     * <code>int32 dist2 = 2;</code>
     * @return The dist2.
     */
    public int getDist2() {
      return dist2_;
    }

    public static final int DIST3_FIELD_NUMBER = 3;
    private int dist3_;
    /**
     * <code>int32 dist3 = 3;</code>
     * @return The dist3.
     */
    public int getDist3() {
      return dist3_;
    }

    public static final int DIST4_FIELD_NUMBER = 4;
    private int dist4_;
    /**
     * <code>int32 dist4 = 4;</code>
     * @return The dist4.
     */
    public int getDist4() {
      return dist4_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dist1_ != 0) {
        output.writeInt32(1, dist1_);
      }
      if (dist2_ != 0) {
        output.writeInt32(2, dist2_);
      }
      if (dist3_ != 0) {
        output.writeInt32(3, dist3_);
      }
      if (dist4_ != 0) {
        output.writeInt32(4, dist4_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dist1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dist1_);
      }
      if (dist2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dist2_);
      }
      if (dist3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dist3_);
      }
      if (dist4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dist4_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TeleCommunication.DistancesMessage)) {
        return super.equals(obj);
      }
      TeleCommunication.DistancesMessage other = (TeleCommunication.DistancesMessage) obj;

      if (getDist1()
          != other.getDist1()) return false;
      if (getDist2()
          != other.getDist2()) return false;
      if (getDist3()
          != other.getDist3()) return false;
      if (getDist4()
          != other.getDist4()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DIST1_FIELD_NUMBER;
      hash = (53 * hash) + getDist1();
      hash = (37 * hash) + DIST2_FIELD_NUMBER;
      hash = (53 * hash) + getDist2();
      hash = (37 * hash) + DIST3_FIELD_NUMBER;
      hash = (53 * hash) + getDist3();
      hash = (37 * hash) + DIST4_FIELD_NUMBER;
      hash = (53 * hash) + getDist4();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TeleCommunication.DistancesMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.DistancesMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.DistancesMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.DistancesMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TeleCommunication.DistancesMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.DistancesMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TeleCommunication.DistancesMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DistancesMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DistancesMessage)
        TeleCommunication.DistancesMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TeleCommunication.internal_static_DistancesMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TeleCommunication.internal_static_DistancesMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeleCommunication.DistancesMessage.class, TeleCommunication.DistancesMessage.Builder.class);
      }

      // Construct using TeleCommunication.DistancesMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dist1_ = 0;

        dist2_ = 0;

        dist3_ = 0;

        dist4_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TeleCommunication.internal_static_DistancesMessage_descriptor;
      }

      @java.lang.Override
      public TeleCommunication.DistancesMessage getDefaultInstanceForType() {
        return TeleCommunication.DistancesMessage.getDefaultInstance();
      }

      @java.lang.Override
      public TeleCommunication.DistancesMessage build() {
        TeleCommunication.DistancesMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TeleCommunication.DistancesMessage buildPartial() {
        TeleCommunication.DistancesMessage result = new TeleCommunication.DistancesMessage(this);
        result.dist1_ = dist1_;
        result.dist2_ = dist2_;
        result.dist3_ = dist3_;
        result.dist4_ = dist4_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeleCommunication.DistancesMessage) {
          return mergeFrom((TeleCommunication.DistancesMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeleCommunication.DistancesMessage other) {
        if (other == TeleCommunication.DistancesMessage.getDefaultInstance()) return this;
        if (other.getDist1() != 0) {
          setDist1(other.getDist1());
        }
        if (other.getDist2() != 0) {
          setDist2(other.getDist2());
        }
        if (other.getDist3() != 0) {
          setDist3(other.getDist3());
        }
        if (other.getDist4() != 0) {
          setDist4(other.getDist4());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeleCommunication.DistancesMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeleCommunication.DistancesMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dist1_ ;
      /**
       * <code>int32 dist1 = 1;</code>
       * @return The dist1.
       */
      public int getDist1() {
        return dist1_;
      }
      /**
       * <code>int32 dist1 = 1;</code>
       * @param value The dist1 to set.
       * @return This builder for chaining.
       */
      public Builder setDist1(int value) {
        
        dist1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dist1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDist1() {
        
        dist1_ = 0;
        onChanged();
        return this;
      }

      private int dist2_ ;
      /**
       * <code>int32 dist2 = 2;</code>
       * @return The dist2.
       */
      public int getDist2() {
        return dist2_;
      }
      /**
       * <code>int32 dist2 = 2;</code>
       * @param value The dist2 to set.
       * @return This builder for chaining.
       */
      public Builder setDist2(int value) {
        
        dist2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dist2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDist2() {
        
        dist2_ = 0;
        onChanged();
        return this;
      }

      private int dist3_ ;
      /**
       * <code>int32 dist3 = 3;</code>
       * @return The dist3.
       */
      public int getDist3() {
        return dist3_;
      }
      /**
       * <code>int32 dist3 = 3;</code>
       * @param value The dist3 to set.
       * @return This builder for chaining.
       */
      public Builder setDist3(int value) {
        
        dist3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dist3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDist3() {
        
        dist3_ = 0;
        onChanged();
        return this;
      }

      private int dist4_ ;
      /**
       * <code>int32 dist4 = 4;</code>
       * @return The dist4.
       */
      public int getDist4() {
        return dist4_;
      }
      /**
       * <code>int32 dist4 = 4;</code>
       * @param value The dist4 to set.
       * @return This builder for chaining.
       */
      public Builder setDist4(int value) {
        
        dist4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dist4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDist4() {
        
        dist4_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DistancesMessage)
    }

    // @@protoc_insertion_point(class_scope:DistancesMessage)
    private static final TeleCommunication.DistancesMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TeleCommunication.DistancesMessage();
    }

    public static TeleCommunication.DistancesMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DistancesMessage>
        PARSER = new com.google.protobuf.AbstractParser<DistancesMessage>() {
      @java.lang.Override
      public DistancesMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DistancesMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DistancesMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DistancesMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TeleCommunication.DistancesMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CollisionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CollisionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool collision = 1;</code>
     * @return The collision.
     */
    boolean getCollision();
  }
  /**
   * Protobuf type {@code CollisionMessage}
   */
  public  static final class CollisionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CollisionMessage)
      CollisionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CollisionMessage.newBuilder() to construct.
    private CollisionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CollisionMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CollisionMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CollisionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              collision_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TeleCommunication.internal_static_CollisionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TeleCommunication.internal_static_CollisionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TeleCommunication.CollisionMessage.class, TeleCommunication.CollisionMessage.Builder.class);
    }

    public static final int COLLISION_FIELD_NUMBER = 1;
    private boolean collision_;
    /**
     * <code>bool collision = 1;</code>
     * @return The collision.
     */
    public boolean getCollision() {
      return collision_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (collision_ != false) {
        output.writeBool(1, collision_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (collision_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, collision_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TeleCommunication.CollisionMessage)) {
        return super.equals(obj);
      }
      TeleCommunication.CollisionMessage other = (TeleCommunication.CollisionMessage) obj;

      if (getCollision()
          != other.getCollision()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLLISION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCollision());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TeleCommunication.CollisionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.CollisionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TeleCommunication.CollisionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.CollisionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TeleCommunication.CollisionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TeleCommunication.CollisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TeleCommunication.CollisionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CollisionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CollisionMessage)
        TeleCommunication.CollisionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TeleCommunication.internal_static_CollisionMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TeleCommunication.internal_static_CollisionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TeleCommunication.CollisionMessage.class, TeleCommunication.CollisionMessage.Builder.class);
      }

      // Construct using TeleCommunication.CollisionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        collision_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TeleCommunication.internal_static_CollisionMessage_descriptor;
      }

      @java.lang.Override
      public TeleCommunication.CollisionMessage getDefaultInstanceForType() {
        return TeleCommunication.CollisionMessage.getDefaultInstance();
      }

      @java.lang.Override
      public TeleCommunication.CollisionMessage build() {
        TeleCommunication.CollisionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TeleCommunication.CollisionMessage buildPartial() {
        TeleCommunication.CollisionMessage result = new TeleCommunication.CollisionMessage(this);
        result.collision_ = collision_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TeleCommunication.CollisionMessage) {
          return mergeFrom((TeleCommunication.CollisionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TeleCommunication.CollisionMessage other) {
        if (other == TeleCommunication.CollisionMessage.getDefaultInstance()) return this;
        if (other.getCollision() != false) {
          setCollision(other.getCollision());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TeleCommunication.CollisionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TeleCommunication.CollisionMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean collision_ ;
      /**
       * <code>bool collision = 1;</code>
       * @return The collision.
       */
      public boolean getCollision() {
        return collision_;
      }
      /**
       * <code>bool collision = 1;</code>
       * @param value The collision to set.
       * @return This builder for chaining.
       */
      public Builder setCollision(boolean value) {
        
        collision_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool collision = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCollision() {
        
        collision_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CollisionMessage)
    }

    // @@protoc_insertion_point(class_scope:CollisionMessage)
    private static final TeleCommunication.CollisionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TeleCommunication.CollisionMessage();
    }

    public static TeleCommunication.CollisionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CollisionMessage>
        PARSER = new com.google.protobuf.AbstractParser<CollisionMessage>() {
      @java.lang.Override
      public CollisionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CollisionMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CollisionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CollisionMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TeleCommunication.CollisionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DistancesMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DistancesMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CollisionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CollisionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027TeleCommunication.proto\"`\n\016ControlMess" +
      "age\022\017\n\007speed_x\030\001 \001(\005\022\017\n\007speed_y\030\002 \001(\005\022\021\n" +
      "\tspeed_rot\030\003 \001(\005\022\013\n\003pan\030\004 \001(\005\022\014\n\004tilt\030\005 " +
      "\001(\005\"N\n\020DistancesMessage\022\r\n\005dist1\030\001 \001(\005\022\r" +
      "\n\005dist2\030\002 \001(\005\022\r\n\005dist3\030\003 \001(\005\022\r\n\005dist4\030\004 " +
      "\001(\005\"%\n\020CollisionMessage\022\021\n\tcollision\030\001 \001" +
      "(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ControlMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ControlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlMessage_descriptor,
        new java.lang.String[] { "SpeedX", "SpeedY", "SpeedRot", "Pan", "Tilt", });
    internal_static_DistancesMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DistancesMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DistancesMessage_descriptor,
        new java.lang.String[] { "Dist1", "Dist2", "Dist3", "Dist4", });
    internal_static_CollisionMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CollisionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CollisionMessage_descriptor,
        new java.lang.String[] { "Collision", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
